title: "Trompa's Snippets"
description: "Useful scripts, aliases, and workflow hacks"
theme: jekyll-theme-hacker
paginate: 5
paginate_path: "/page:num/"
date_format: "%B %-d, %Y"
plugins:
  - jekyll-paginate
